language: r
cache: packages

notifications:
  email:
    recipients:
     - alerts@jumpingrivers.support
    on_success: change
    on_failure: change

r_packages:
  - drat

before_install:
  - tlmgr install fancyvrb units
  - sudo apt-get install libgit2-dev

before_script:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/test_deploy.sh
  - if [ ${TRAVIS_PULL_REQUEST} = "false" ] && [ $TRAVIS_BRANCH = "master" ]; then bash test_deploy.sh; fi
  - rm test_deploy.sh

after_script:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'if(length(lintr::lint_package()) > 0) stop("Fix lint")'


after_success:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
